FROM node:22-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json ./
COPY .env .env ./
RUN npm install
COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/.env .env
ENV NODE_ENV "production"
EXPOSE 80
CMD ["node", "dist/api-gateway.js"]
