services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend-dist:/usr/share/nginx/html:ro

    depends_on:
      - frontend
      - api-gateway
    networks:
      - app-network

  frontend:
    build: ./front-react-alegra
    container_name: frontend
    volumes:
      - frontend-dist:/frontend
    depends_on:
      - api-gateway
    networks:
      - app-network

  api-gateway:
    build: ./micro-api-gateway
    container_name: api-gateway
    expose:
      - "2000"
    depends_on:
      - orders
      - kitchen
      - storage
    networks:
      - app-network

  orders:
    build: ./micro-orders
    container_name: orders
    expose:
      - "3000"
    depends_on:
      - redis
      - mysql-orders
    environment:
      DB_HOST: mysql-orders
      DB_PORT: 3306
      TRANSPORTER_HOST: redis
      TRANSPORTER_PORT: 6379
    networks:
      - app-network

  kitchen:
    build: ./micro-kitchen
    container_name: kitchen
    expose:
      - "4000"
    depends_on:
      - redis
      - mysql-kitchen
    environment:
      DB_HOST: mysql-kitchen
      DB_PORT: 3306
      TRANSPORTER_HOST: redis
      TRANSPORTER_PORT: 6379
    networks:
      - app-network

  storage:
    build: ./micro-storage
    container_name: storage
    expose:
      - "5000"
    depends_on:
      - redis
      - mysql-storage
    environment:
      DB_HOST: mysql-storage
      DB_PORT: 3306
      TRANSPORTER_HOST: redis
      TRANSPORTER_PORT: 6379
    networks:
      - app-network

  redis:
    image: redis/redis-stack-server
    container_name: redis
    restart: always
    expose:
      - "6379"
    networks:
      - app-network

  mysql-orders:
    image: mysql:8
    container_name: mysql-orders
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_alegra_orders
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - mysql-orders-data:/var/lib/mysql
      - ./scripts/orders:/docker-entrypoint-initdb.d

    networks:
      - app-network

  mysql-kitchen:
    image: mysql:8
    container_name: mysql-kitchen
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_alegra_kitchen
    ports:
      - "3308:3306"
    expose:
      - "3306"
    volumes:
      - mysql-kitchen-data:/var/lib/mysql
      - ./scripts/kitchen:/docker-entrypoint-initdb.d
    networks:
      - app-network

  mysql-storage:
    image: mysql:8
    container_name: mysql-storage
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_alegra_storage
    ports:
      - "3309:3306"
    expose:
      - "3306"
    volumes:
      - mysql-storage-data:/var/lib/mysql
      - ./scripts/storage:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-orders-data:
  mysql-kitchen-data:
  mysql-storage-data:
  frontend-dist:
