FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

FROM alpine:latest

WORKDIR /frontend

COPY --from=builder /app/dist /frontend



